// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meshData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_meshData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_meshData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
#include "vboData.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_meshData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_meshData_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
class meshData_proto;
struct meshData_protoDefaultTypeInternal;
extern meshData_protoDefaultTypeInternal _meshData_proto_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::meshData_proto* Arena::CreateMaybeMessage<::meshData_proto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum meshData_proto_RENDER_MODE : int {
  meshData_proto_RENDER_MODE_MODE_POINTS = 0,
  meshData_proto_RENDER_MODE_MODE_LINE = 1,
  meshData_proto_RENDER_MODE_MODE_LINE_LOOP = 2,
  meshData_proto_RENDER_MODE_MODE_LINE_STRIP = 3,
  meshData_proto_RENDER_MODE_MODE_TRIANGLES = 4,
  meshData_proto_RENDER_MODE_MODE_TRIANGLE_STRIP = 5,
  meshData_proto_RENDER_MODE_MODE_TRIANGLE_FAN = 6,
  meshData_proto_RENDER_MODE_meshData_proto_RENDER_MODE_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  meshData_proto_RENDER_MODE_meshData_proto_RENDER_MODE_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool meshData_proto_RENDER_MODE_IsValid(int value);
constexpr meshData_proto_RENDER_MODE meshData_proto_RENDER_MODE_RENDER_MODE_MIN = meshData_proto_RENDER_MODE_MODE_POINTS;
constexpr meshData_proto_RENDER_MODE meshData_proto_RENDER_MODE_RENDER_MODE_MAX = meshData_proto_RENDER_MODE_MODE_TRIANGLE_FAN;
constexpr int meshData_proto_RENDER_MODE_RENDER_MODE_ARRAYSIZE = meshData_proto_RENDER_MODE_RENDER_MODE_MAX + 1;

const std::string& meshData_proto_RENDER_MODE_Name(meshData_proto_RENDER_MODE value);
template<typename T>
inline const std::string& meshData_proto_RENDER_MODE_Name(T enum_t_value) {
  static_assert(::std::is_same<T, meshData_proto_RENDER_MODE>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function meshData_proto_RENDER_MODE_Name.");
  return meshData_proto_RENDER_MODE_Name(static_cast<meshData_proto_RENDER_MODE>(enum_t_value));
}
bool meshData_proto_RENDER_MODE_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, meshData_proto_RENDER_MODE* value);
// ===================================================================

class meshData_proto final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:meshData_proto) */ {
 public:
  inline meshData_proto() : meshData_proto(nullptr) {}
  ~meshData_proto() override;
  explicit constexpr meshData_proto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  meshData_proto(const meshData_proto& from);
  meshData_proto(meshData_proto&& from) noexcept
    : meshData_proto() {
    *this = ::std::move(from);
  }

  inline meshData_proto& operator=(const meshData_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline meshData_proto& operator=(meshData_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const meshData_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const meshData_proto* internal_default_instance() {
    return reinterpret_cast<const meshData_proto*>(
               &_meshData_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(meshData_proto& a, meshData_proto& b) {
    a.Swap(&b);
  }
  inline void Swap(meshData_proto* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(meshData_proto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline meshData_proto* New() const final {
    return new meshData_proto();
  }

  meshData_proto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<meshData_proto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const meshData_proto& from);
  void MergeFrom(const meshData_proto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(meshData_proto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "meshData_proto";
  }
  protected:
  explicit meshData_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef meshData_proto_RENDER_MODE RENDER_MODE;
  static constexpr RENDER_MODE MODE_POINTS =
    meshData_proto_RENDER_MODE_MODE_POINTS;
  static constexpr RENDER_MODE MODE_LINE =
    meshData_proto_RENDER_MODE_MODE_LINE;
  static constexpr RENDER_MODE MODE_LINE_LOOP =
    meshData_proto_RENDER_MODE_MODE_LINE_LOOP;
  static constexpr RENDER_MODE MODE_LINE_STRIP =
    meshData_proto_RENDER_MODE_MODE_LINE_STRIP;
  static constexpr RENDER_MODE MODE_TRIANGLES =
    meshData_proto_RENDER_MODE_MODE_TRIANGLES;
  static constexpr RENDER_MODE MODE_TRIANGLE_STRIP =
    meshData_proto_RENDER_MODE_MODE_TRIANGLE_STRIP;
  static constexpr RENDER_MODE MODE_TRIANGLE_FAN =
    meshData_proto_RENDER_MODE_MODE_TRIANGLE_FAN;
  static inline bool RENDER_MODE_IsValid(int value) {
    return meshData_proto_RENDER_MODE_IsValid(value);
  }
  static constexpr RENDER_MODE RENDER_MODE_MIN =
    meshData_proto_RENDER_MODE_RENDER_MODE_MIN;
  static constexpr RENDER_MODE RENDER_MODE_MAX =
    meshData_proto_RENDER_MODE_RENDER_MODE_MAX;
  static constexpr int RENDER_MODE_ARRAYSIZE =
    meshData_proto_RENDER_MODE_RENDER_MODE_ARRAYSIZE;
  template<typename T>
  static inline const std::string& RENDER_MODE_Name(T enum_t_value) {
    static_assert(::std::is_same<T, RENDER_MODE>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function RENDER_MODE_Name.");
    return meshData_proto_RENDER_MODE_Name(enum_t_value);
  }
  static inline bool RENDER_MODE_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      RENDER_MODE* value) {
    return meshData_proto_RENDER_MODE_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kPNameFieldNumber = 2,
    kVboVertFieldNumber = 4,
    kVboNormFieldNumber = 5,
    kVboUvFieldNumber = 6,
    kVboIndexFieldNumber = 7,
    kVboColorFieldNumber = 8,
    kEnabledFieldNumber = 1,
    kModeFieldNumber = 3,
    kTriCountFieldNumber = 9,
    kVertCountFieldNumber = 10,
    kMaterialIndexFieldNumber = 11,
    kJointIndexFieldNumber = 12,
    kParentJointIndexFieldNumber = 13,
  };
  // bytes pName = 2;
  void clear_pname();
  const std::string& pname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_pname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_pname();
  PROTOBUF_MUST_USE_RESULT std::string* release_pname();
  void set_allocated_pname(std::string* pname);
  private:
  const std::string& _internal_pname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pname(const std::string& value);
  std::string* _internal_mutable_pname();
  public:

  // .vboData_proto vbo_vert = 4;
  bool has_vbo_vert() const;
  private:
  bool _internal_has_vbo_vert() const;
  public:
  void clear_vbo_vert();
  const ::vboData_proto& vbo_vert() const;
  PROTOBUF_MUST_USE_RESULT ::vboData_proto* release_vbo_vert();
  ::vboData_proto* mutable_vbo_vert();
  void set_allocated_vbo_vert(::vboData_proto* vbo_vert);
  private:
  const ::vboData_proto& _internal_vbo_vert() const;
  ::vboData_proto* _internal_mutable_vbo_vert();
  public:
  void unsafe_arena_set_allocated_vbo_vert(
      ::vboData_proto* vbo_vert);
  ::vboData_proto* unsafe_arena_release_vbo_vert();

  // .vboData_proto vbo_norm = 5;
  bool has_vbo_norm() const;
  private:
  bool _internal_has_vbo_norm() const;
  public:
  void clear_vbo_norm();
  const ::vboData_proto& vbo_norm() const;
  PROTOBUF_MUST_USE_RESULT ::vboData_proto* release_vbo_norm();
  ::vboData_proto* mutable_vbo_norm();
  void set_allocated_vbo_norm(::vboData_proto* vbo_norm);
  private:
  const ::vboData_proto& _internal_vbo_norm() const;
  ::vboData_proto* _internal_mutable_vbo_norm();
  public:
  void unsafe_arena_set_allocated_vbo_norm(
      ::vboData_proto* vbo_norm);
  ::vboData_proto* unsafe_arena_release_vbo_norm();

  // .vboData_proto vbo_uv = 6;
  bool has_vbo_uv() const;
  private:
  bool _internal_has_vbo_uv() const;
  public:
  void clear_vbo_uv();
  const ::vboData_proto& vbo_uv() const;
  PROTOBUF_MUST_USE_RESULT ::vboData_proto* release_vbo_uv();
  ::vboData_proto* mutable_vbo_uv();
  void set_allocated_vbo_uv(::vboData_proto* vbo_uv);
  private:
  const ::vboData_proto& _internal_vbo_uv() const;
  ::vboData_proto* _internal_mutable_vbo_uv();
  public:
  void unsafe_arena_set_allocated_vbo_uv(
      ::vboData_proto* vbo_uv);
  ::vboData_proto* unsafe_arena_release_vbo_uv();

  // .vboData_proto vbo_index = 7;
  bool has_vbo_index() const;
  private:
  bool _internal_has_vbo_index() const;
  public:
  void clear_vbo_index();
  const ::vboData_proto& vbo_index() const;
  PROTOBUF_MUST_USE_RESULT ::vboData_proto* release_vbo_index();
  ::vboData_proto* mutable_vbo_index();
  void set_allocated_vbo_index(::vboData_proto* vbo_index);
  private:
  const ::vboData_proto& _internal_vbo_index() const;
  ::vboData_proto* _internal_mutable_vbo_index();
  public:
  void unsafe_arena_set_allocated_vbo_index(
      ::vboData_proto* vbo_index);
  ::vboData_proto* unsafe_arena_release_vbo_index();

  // .vboData_proto vbo_color = 8;
  bool has_vbo_color() const;
  private:
  bool _internal_has_vbo_color() const;
  public:
  void clear_vbo_color();
  const ::vboData_proto& vbo_color() const;
  PROTOBUF_MUST_USE_RESULT ::vboData_proto* release_vbo_color();
  ::vboData_proto* mutable_vbo_color();
  void set_allocated_vbo_color(::vboData_proto* vbo_color);
  private:
  const ::vboData_proto& _internal_vbo_color() const;
  ::vboData_proto* _internal_mutable_vbo_color();
  public:
  void unsafe_arena_set_allocated_vbo_color(
      ::vboData_proto* vbo_color);
  ::vboData_proto* unsafe_arena_release_vbo_color();

  // bool enabled = 1;
  void clear_enabled();
  bool enabled() const;
  void set_enabled(bool value);
  private:
  bool _internal_enabled() const;
  void _internal_set_enabled(bool value);
  public:

  // .meshData_proto.RENDER_MODE mode = 3;
  void clear_mode();
  ::meshData_proto_RENDER_MODE mode() const;
  void set_mode(::meshData_proto_RENDER_MODE value);
  private:
  ::meshData_proto_RENDER_MODE _internal_mode() const;
  void _internal_set_mode(::meshData_proto_RENDER_MODE value);
  public:

  // uint32 triCount = 9;
  void clear_tricount();
  ::PROTOBUF_NAMESPACE_ID::uint32 tricount() const;
  void set_tricount(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_tricount() const;
  void _internal_set_tricount(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 vertCount = 10;
  void clear_vertcount();
  ::PROTOBUF_NAMESPACE_ID::uint32 vertcount() const;
  void set_vertcount(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_vertcount() const;
  void _internal_set_vertcount(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 materialIndex = 11;
  void clear_materialindex();
  ::PROTOBUF_NAMESPACE_ID::uint32 materialindex() const;
  void set_materialindex(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_materialindex() const;
  void _internal_set_materialindex(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // sint32 jointIndex = 12;
  void clear_jointindex();
  ::PROTOBUF_NAMESPACE_ID::int32 jointindex() const;
  void set_jointindex(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_jointindex() const;
  void _internal_set_jointindex(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // sint32 parentJointIndex = 13;
  void clear_parentjointindex();
  ::PROTOBUF_NAMESPACE_ID::int32 parentjointindex() const;
  void set_parentjointindex(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_parentjointindex() const;
  void _internal_set_parentjointindex(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:meshData_proto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pname_;
  ::vboData_proto* vbo_vert_;
  ::vboData_proto* vbo_norm_;
  ::vboData_proto* vbo_uv_;
  ::vboData_proto* vbo_index_;
  ::vboData_proto* vbo_color_;
  bool enabled_;
  int mode_;
  ::PROTOBUF_NAMESPACE_ID::uint32 tricount_;
  ::PROTOBUF_NAMESPACE_ID::uint32 vertcount_;
  ::PROTOBUF_NAMESPACE_ID::uint32 materialindex_;
  ::PROTOBUF_NAMESPACE_ID::int32 jointindex_;
  ::PROTOBUF_NAMESPACE_ID::int32 parentjointindex_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_meshData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// meshData_proto

// bool enabled = 1;
inline void meshData_proto::clear_enabled() {
  enabled_ = false;
}
inline bool meshData_proto::_internal_enabled() const {
  return enabled_;
}
inline bool meshData_proto::enabled() const {
  // @@protoc_insertion_point(field_get:meshData_proto.enabled)
  return _internal_enabled();
}
inline void meshData_proto::_internal_set_enabled(bool value) {
  
  enabled_ = value;
}
inline void meshData_proto::set_enabled(bool value) {
  _internal_set_enabled(value);
  // @@protoc_insertion_point(field_set:meshData_proto.enabled)
}

// bytes pName = 2;
inline void meshData_proto::clear_pname() {
  pname_.ClearToEmpty();
}
inline const std::string& meshData_proto::pname() const {
  // @@protoc_insertion_point(field_get:meshData_proto.pName)
  return _internal_pname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void meshData_proto::set_pname(ArgT0&& arg0, ArgT... args) {
 
 pname_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:meshData_proto.pName)
}
inline std::string* meshData_proto::mutable_pname() {
  std::string* _s = _internal_mutable_pname();
  // @@protoc_insertion_point(field_mutable:meshData_proto.pName)
  return _s;
}
inline const std::string& meshData_proto::_internal_pname() const {
  return pname_.Get();
}
inline void meshData_proto::_internal_set_pname(const std::string& value) {
  
  pname_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* meshData_proto::_internal_mutable_pname() {
  
  return pname_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* meshData_proto::release_pname() {
  // @@protoc_insertion_point(field_release:meshData_proto.pName)
  return pname_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void meshData_proto::set_allocated_pname(std::string* pname) {
  if (pname != nullptr) {
    
  } else {
    
  }
  pname_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), pname,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.pName)
}

// .meshData_proto.RENDER_MODE mode = 3;
inline void meshData_proto::clear_mode() {
  mode_ = 0;
}
inline ::meshData_proto_RENDER_MODE meshData_proto::_internal_mode() const {
  return static_cast< ::meshData_proto_RENDER_MODE >(mode_);
}
inline ::meshData_proto_RENDER_MODE meshData_proto::mode() const {
  // @@protoc_insertion_point(field_get:meshData_proto.mode)
  return _internal_mode();
}
inline void meshData_proto::_internal_set_mode(::meshData_proto_RENDER_MODE value) {
  
  mode_ = value;
}
inline void meshData_proto::set_mode(::meshData_proto_RENDER_MODE value) {
  _internal_set_mode(value);
  // @@protoc_insertion_point(field_set:meshData_proto.mode)
}

// .vboData_proto vbo_vert = 4;
inline bool meshData_proto::_internal_has_vbo_vert() const {
  return this != internal_default_instance() && vbo_vert_ != nullptr;
}
inline bool meshData_proto::has_vbo_vert() const {
  return _internal_has_vbo_vert();
}
inline const ::vboData_proto& meshData_proto::_internal_vbo_vert() const {
  const ::vboData_proto* p = vbo_vert_;
  return p != nullptr ? *p : reinterpret_cast<const ::vboData_proto&>(
      ::_vboData_proto_default_instance_);
}
inline const ::vboData_proto& meshData_proto::vbo_vert() const {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_vert)
  return _internal_vbo_vert();
}
inline void meshData_proto::unsafe_arena_set_allocated_vbo_vert(
    ::vboData_proto* vbo_vert) {
  if (GetArenaForAllocation() == nullptr) {
    delete static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_vert_);
  }
  vbo_vert_ = vbo_vert;
  if (vbo_vert) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:meshData_proto.vbo_vert)
}
inline ::vboData_proto* meshData_proto::release_vbo_vert() {
  
  ::vboData_proto* temp = vbo_vert_;
  vbo_vert_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::vboData_proto* meshData_proto::unsafe_arena_release_vbo_vert() {
  // @@protoc_insertion_point(field_release:meshData_proto.vbo_vert)
  
  ::vboData_proto* temp = vbo_vert_;
  vbo_vert_ = nullptr;
  return temp;
}
inline ::vboData_proto* meshData_proto::_internal_mutable_vbo_vert() {
  
  if (vbo_vert_ == nullptr) {
    auto* p = CreateMaybeMessage<::vboData_proto>(GetArenaForAllocation());
    vbo_vert_ = p;
  }
  return vbo_vert_;
}
inline ::vboData_proto* meshData_proto::mutable_vbo_vert() {
  ::vboData_proto* _msg = _internal_mutable_vbo_vert();
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_vert)
  return _msg;
}
inline void meshData_proto::set_allocated_vbo_vert(::vboData_proto* vbo_vert) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete static_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_vert_);
  }
  if (vbo_vert) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_vert));
    if (message_arena != submessage_arena) {
      vbo_vert = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vbo_vert, submessage_arena);
    }
    
  } else {
    
  }
  vbo_vert_ = vbo_vert;
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.vbo_vert)
}

// .vboData_proto vbo_norm = 5;
inline bool meshData_proto::_internal_has_vbo_norm() const {
  return this != internal_default_instance() && vbo_norm_ != nullptr;
}
inline bool meshData_proto::has_vbo_norm() const {
  return _internal_has_vbo_norm();
}
inline const ::vboData_proto& meshData_proto::_internal_vbo_norm() const {
  const ::vboData_proto* p = vbo_norm_;
  return p != nullptr ? *p : reinterpret_cast<const ::vboData_proto&>(
      ::_vboData_proto_default_instance_);
}
inline const ::vboData_proto& meshData_proto::vbo_norm() const {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_norm)
  return _internal_vbo_norm();
}
inline void meshData_proto::unsafe_arena_set_allocated_vbo_norm(
    ::vboData_proto* vbo_norm) {
  if (GetArenaForAllocation() == nullptr) {
    delete static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_norm_);
  }
  vbo_norm_ = vbo_norm;
  if (vbo_norm) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:meshData_proto.vbo_norm)
}
inline ::vboData_proto* meshData_proto::release_vbo_norm() {
  
  ::vboData_proto* temp = vbo_norm_;
  vbo_norm_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::vboData_proto* meshData_proto::unsafe_arena_release_vbo_norm() {
  // @@protoc_insertion_point(field_release:meshData_proto.vbo_norm)
  
  ::vboData_proto* temp = vbo_norm_;
  vbo_norm_ = nullptr;
  return temp;
}
inline ::vboData_proto* meshData_proto::_internal_mutable_vbo_norm() {
  
  if (vbo_norm_ == nullptr) {
    auto* p = CreateMaybeMessage<::vboData_proto>(GetArenaForAllocation());
    vbo_norm_ = p;
  }
  return vbo_norm_;
}
inline ::vboData_proto* meshData_proto::mutable_vbo_norm() {
  ::vboData_proto* _msg = _internal_mutable_vbo_norm();
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_norm)
  return _msg;
}
inline void meshData_proto::set_allocated_vbo_norm(::vboData_proto* vbo_norm) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete static_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_norm_);
  }
  if (vbo_norm) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_norm));
    if (message_arena != submessage_arena) {
      vbo_norm = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vbo_norm, submessage_arena);
    }
    
  } else {
    
  }
  vbo_norm_ = vbo_norm;
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.vbo_norm)
}

// .vboData_proto vbo_uv = 6;
inline bool meshData_proto::_internal_has_vbo_uv() const {
  return this != internal_default_instance() && vbo_uv_ != nullptr;
}
inline bool meshData_proto::has_vbo_uv() const {
  return _internal_has_vbo_uv();
}
inline const ::vboData_proto& meshData_proto::_internal_vbo_uv() const {
  const ::vboData_proto* p = vbo_uv_;
  return p != nullptr ? *p : reinterpret_cast<const ::vboData_proto&>(
      ::_vboData_proto_default_instance_);
}
inline const ::vboData_proto& meshData_proto::vbo_uv() const {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_uv)
  return _internal_vbo_uv();
}
inline void meshData_proto::unsafe_arena_set_allocated_vbo_uv(
    ::vboData_proto* vbo_uv) {
  if (GetArenaForAllocation() == nullptr) {
    delete static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_uv_);
  }
  vbo_uv_ = vbo_uv;
  if (vbo_uv) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:meshData_proto.vbo_uv)
}
inline ::vboData_proto* meshData_proto::release_vbo_uv() {
  
  ::vboData_proto* temp = vbo_uv_;
  vbo_uv_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::vboData_proto* meshData_proto::unsafe_arena_release_vbo_uv() {
  // @@protoc_insertion_point(field_release:meshData_proto.vbo_uv)
  
  ::vboData_proto* temp = vbo_uv_;
  vbo_uv_ = nullptr;
  return temp;
}
inline ::vboData_proto* meshData_proto::_internal_mutable_vbo_uv() {
  
  if (vbo_uv_ == nullptr) {
    auto* p = CreateMaybeMessage<::vboData_proto>(GetArenaForAllocation());
    vbo_uv_ = p;
  }
  return vbo_uv_;
}
inline ::vboData_proto* meshData_proto::mutable_vbo_uv() {
  ::vboData_proto* _msg = _internal_mutable_vbo_uv();
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_uv)
  return _msg;
}
inline void meshData_proto::set_allocated_vbo_uv(::vboData_proto* vbo_uv) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete static_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_uv_);
  }
  if (vbo_uv) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_uv));
    if (message_arena != submessage_arena) {
      vbo_uv = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vbo_uv, submessage_arena);
    }
    
  } else {
    
  }
  vbo_uv_ = vbo_uv;
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.vbo_uv)
}

// .vboData_proto vbo_index = 7;
inline bool meshData_proto::_internal_has_vbo_index() const {
  return this != internal_default_instance() && vbo_index_ != nullptr;
}
inline bool meshData_proto::has_vbo_index() const {
  return _internal_has_vbo_index();
}
inline const ::vboData_proto& meshData_proto::_internal_vbo_index() const {
  const ::vboData_proto* p = vbo_index_;
  return p != nullptr ? *p : reinterpret_cast<const ::vboData_proto&>(
      ::_vboData_proto_default_instance_);
}
inline const ::vboData_proto& meshData_proto::vbo_index() const {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_index)
  return _internal_vbo_index();
}
inline void meshData_proto::unsafe_arena_set_allocated_vbo_index(
    ::vboData_proto* vbo_index) {
  if (GetArenaForAllocation() == nullptr) {
    delete static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_index_);
  }
  vbo_index_ = vbo_index;
  if (vbo_index) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:meshData_proto.vbo_index)
}
inline ::vboData_proto* meshData_proto::release_vbo_index() {
  
  ::vboData_proto* temp = vbo_index_;
  vbo_index_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::vboData_proto* meshData_proto::unsafe_arena_release_vbo_index() {
  // @@protoc_insertion_point(field_release:meshData_proto.vbo_index)
  
  ::vboData_proto* temp = vbo_index_;
  vbo_index_ = nullptr;
  return temp;
}
inline ::vboData_proto* meshData_proto::_internal_mutable_vbo_index() {
  
  if (vbo_index_ == nullptr) {
    auto* p = CreateMaybeMessage<::vboData_proto>(GetArenaForAllocation());
    vbo_index_ = p;
  }
  return vbo_index_;
}
inline ::vboData_proto* meshData_proto::mutable_vbo_index() {
  ::vboData_proto* _msg = _internal_mutable_vbo_index();
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_index)
  return _msg;
}
inline void meshData_proto::set_allocated_vbo_index(::vboData_proto* vbo_index) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete static_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_index_);
  }
  if (vbo_index) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_index));
    if (message_arena != submessage_arena) {
      vbo_index = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vbo_index, submessage_arena);
    }
    
  } else {
    
  }
  vbo_index_ = vbo_index;
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.vbo_index)
}

// .vboData_proto vbo_color = 8;
inline bool meshData_proto::_internal_has_vbo_color() const {
  return this != internal_default_instance() && vbo_color_ != nullptr;
}
inline bool meshData_proto::has_vbo_color() const {
  return _internal_has_vbo_color();
}
inline const ::vboData_proto& meshData_proto::_internal_vbo_color() const {
  const ::vboData_proto* p = vbo_color_;
  return p != nullptr ? *p : reinterpret_cast<const ::vboData_proto&>(
      ::_vboData_proto_default_instance_);
}
inline const ::vboData_proto& meshData_proto::vbo_color() const {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_color)
  return _internal_vbo_color();
}
inline void meshData_proto::unsafe_arena_set_allocated_vbo_color(
    ::vboData_proto* vbo_color) {
  if (GetArenaForAllocation() == nullptr) {
    delete static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_color_);
  }
  vbo_color_ = vbo_color;
  if (vbo_color) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:meshData_proto.vbo_color)
}
inline ::vboData_proto* meshData_proto::release_vbo_color() {
  
  ::vboData_proto* temp = vbo_color_;
  vbo_color_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::vboData_proto* meshData_proto::unsafe_arena_release_vbo_color() {
  // @@protoc_insertion_point(field_release:meshData_proto.vbo_color)
  
  ::vboData_proto* temp = vbo_color_;
  vbo_color_ = nullptr;
  return temp;
}
inline ::vboData_proto* meshData_proto::_internal_mutable_vbo_color() {
  
  if (vbo_color_ == nullptr) {
    auto* p = CreateMaybeMessage<::vboData_proto>(GetArenaForAllocation());
    vbo_color_ = p;
  }
  return vbo_color_;
}
inline ::vboData_proto* meshData_proto::mutable_vbo_color() {
  ::vboData_proto* _msg = _internal_mutable_vbo_color();
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_color)
  return _msg;
}
inline void meshData_proto::set_allocated_vbo_color(::vboData_proto* vbo_color) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete static_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_color_);
  }
  if (vbo_color) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_color));
    if (message_arena != submessage_arena) {
      vbo_color = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vbo_color, submessage_arena);
    }
    
  } else {
    
  }
  vbo_color_ = vbo_color;
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.vbo_color)
}

// uint32 triCount = 9;
inline void meshData_proto::clear_tricount() {
  tricount_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 meshData_proto::_internal_tricount() const {
  return tricount_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 meshData_proto::tricount() const {
  // @@protoc_insertion_point(field_get:meshData_proto.triCount)
  return _internal_tricount();
}
inline void meshData_proto::_internal_set_tricount(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  tricount_ = value;
}
inline void meshData_proto::set_tricount(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_tricount(value);
  // @@protoc_insertion_point(field_set:meshData_proto.triCount)
}

// uint32 vertCount = 10;
inline void meshData_proto::clear_vertcount() {
  vertcount_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 meshData_proto::_internal_vertcount() const {
  return vertcount_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 meshData_proto::vertcount() const {
  // @@protoc_insertion_point(field_get:meshData_proto.vertCount)
  return _internal_vertcount();
}
inline void meshData_proto::_internal_set_vertcount(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  vertcount_ = value;
}
inline void meshData_proto::set_vertcount(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_vertcount(value);
  // @@protoc_insertion_point(field_set:meshData_proto.vertCount)
}

// uint32 materialIndex = 11;
inline void meshData_proto::clear_materialindex() {
  materialindex_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 meshData_proto::_internal_materialindex() const {
  return materialindex_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 meshData_proto::materialindex() const {
  // @@protoc_insertion_point(field_get:meshData_proto.materialIndex)
  return _internal_materialindex();
}
inline void meshData_proto::_internal_set_materialindex(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  materialindex_ = value;
}
inline void meshData_proto::set_materialindex(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_materialindex(value);
  // @@protoc_insertion_point(field_set:meshData_proto.materialIndex)
}

// sint32 jointIndex = 12;
inline void meshData_proto::clear_jointindex() {
  jointindex_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 meshData_proto::_internal_jointindex() const {
  return jointindex_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 meshData_proto::jointindex() const {
  // @@protoc_insertion_point(field_get:meshData_proto.jointIndex)
  return _internal_jointindex();
}
inline void meshData_proto::_internal_set_jointindex(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  jointindex_ = value;
}
inline void meshData_proto::set_jointindex(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_jointindex(value);
  // @@protoc_insertion_point(field_set:meshData_proto.jointIndex)
}

// sint32 parentJointIndex = 13;
inline void meshData_proto::clear_parentjointindex() {
  parentjointindex_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 meshData_proto::_internal_parentjointindex() const {
  return parentjointindex_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 meshData_proto::parentjointindex() const {
  // @@protoc_insertion_point(field_get:meshData_proto.parentJointIndex)
  return _internal_parentjointindex();
}
inline void meshData_proto::_internal_set_parentjointindex(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  parentjointindex_ = value;
}
inline void meshData_proto::set_parentjointindex(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_parentjointindex(value);
  // @@protoc_insertion_point(field_set:meshData_proto.parentJointIndex)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::meshData_proto_RENDER_MODE> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_meshData_2eproto
